site_name: "Pytred: Python Tools for Refinement and Enhancement of Data"
theme:
  name: "material"
nav:
  - Home: "index.md"
  - API Reference:
      - DataHub: "api_reference/data_hub.md"
      - DataNode: "api_reference/data_node.md"
      - decorators: "api_reference/decorators.md"
plugins:
  - search
  - mkdocs-jupyter
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          rendering:
            show_source: true
          options:
            docstring_style: "numpy"
markdown_extensions:
  - admonition
  - codehilite
